package com.artoo.esaf;

import com.artoo.esaf.TileView;
import com.artoo.esaf.Output;

global Output out;

rule "LAPSalaried - Vintage with esaf very long"
ruleflow-group "lap_salaried"

    when
        $tile : TileView(vintage_esaf == "very_long")
    then
        Ops.calc(out, 10.0d, 10.0d, Ops.BORROWER_CHARC);
        
end

rule "LAPSalaried - Vintage with esaf long"
ruleflow-group "lap_salaried"

    when
        $tile : TileView(vintage_esaf == "long")
    then
        Ops.calc(out, 8.0d, 10.0d, Ops.BORROWER_CHARC);
        
end

rule "LAPSalaried - Vintage with esaf medium"
ruleflow-group "lap_salaried"

    when
       $tile : TileView(vintage_esaf == "medium")
    then
        Ops.calc(out, 6.0d, 10.0d, Ops.BORROWER_CHARC);
        
end

rule "LAPSalaried - Vintage with esaf short"
ruleflow-group "lap_salaried"

    when
        $tile : TileView(vintage_esaf == "short")
    then
        Ops.calc(out, 4.0d, 10.0d, Ops.BORROWER_CHARC);
        
end