package com.artoo.esaf;

import com.artoo.esaf.TileView;
import com.artoo.esaf.Output;

global Output out;

rule "LAPSalaried - Vintage with esaf very long"

    when
        $application : ApplicationView(vintage_with_esaf == "very_long")
    then
        score.setScore(10, 10f);
        
end

rule "LAPSalaried - Vintage with esaf long"

    when
        $application : ApplicationView(loan_type == Constants.LOAN_TYPE_IBL_1,
        	vintage_with_esaf == Constants.VINTAGE_ESAF_LONG)
    then
        score.setScore(8, 10f);
        
end

rule "LAPSalaried - Vintage with esaf medium"

    when
        $application : ApplicationView(loan_type == Constants.LOAN_TYPE_IBL_1,
        	vintage_with_esaf == Constants.VINTAGE_ESAF_MEDIUM)
    then
        score.setScore(6, 10f);
        
end

rule "LAPSalaried - Vintage with esaf short"

    when
        $application : ApplicationView(loan_type == Constants.LOAN_TYPE_IBL_1,
        	vintage_with_esaf == Constants.VINTAGE_ESAF_SHORT)
    then
        score.setScore(4, 10f);
        
end