package com.artoo.esaf;

import org.kie.api.runtime.process.WorkflowProcessInstance;
import com.artoo.esaf.Input;
import com.artoo.esaf.TileView;

rule "test"
ruleflow-group "test"

    when
        $process: WorkflowProcessInstance()
        $tile: TileView()
        
    then
        System.out.println("rule executing");
        $tile.setLoan_type("hyl"); 
        System.out.println("rule executed");
end

rule "test 1"
ruleflow-group "test"

    when
        $process: WorkflowProcessInstance()
        
    then
        System.out.println("rule executing 1");
        TileView  tile = (TileView) $process.getVariable("tile");
        tile.setLoan_type("hyl"); 
        $process.setVariable("tile", tile);
        System.out.println("rule executed 1");
end