package com.artoo.esaf;

import org.kie.api.runtime.process.WorkflowProcessInstance;
import com.artoo.esaf.Input;
import com.artoo.esaf.TileView;


rule "test"
ruleflow-group "test"

    when
        $process: WorkflowProcessInstance()
        
    then
        TileView tile = new TileView();
        tile.setLoan_type("hyl");
        WorkflowProcessInstance $p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance($process.getId()); //casting to WorkflowProcessInstance is essential
        $p.setVariable("tile", tile );
        retract($process);
        System.out.println("test");
end
