package com.artoo.esaf;

import org.kie.api.runtime.process.WorkflowProcessInstance;
import com.artoo.esaf.Input;
import com.artoo.esaf.TileView;

rule "test"
ruleflow-group "test"

    when
        $process: WorkflowProcessInstance()
        
    then
        TileView  tile = (TileView) $process.getVariable("tile");
        tile.setLoan_type("hyl"); 
        $process.setVariable("tile", tile);
        System.out.println("rule executed");
end