package com.artoo.esaf;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditScoringParameter implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CreditScoringParameter() {
    }




}