package com.artoo.esaf;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Input implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "docId")
	private java.lang.String docId;

	public Input() {
	}

	public java.lang.String getDocId() {
		return this.docId;
	}

	public void setDocId(java.lang.String docId) {
		this.docId = docId;
	}

	public Input(java.lang.String docId) {
		this.docId = docId;
	}

}